services:
  gateway:
    build:
      context: ./gateway-service
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    env_file:
      - ./gateway-service/.env

  auth:
    build:
      context: ./auth-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    env_file:
      - ./auth-service/.env

  event:
    build:
      context: ./event-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
    env_file:
      - ./event-service/.env

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
   mongo-data: